CREATE table Book (
    id int GENERATED BY DEFAULT as IDENTITY PRIMARY KEY ,
    title varchar(250) NOT NULL ,
    author varchar(100) NOT NULL ,
    year int NOT NULL ,
    person_id int REFERENCES Person(id) ON DELETE SET NULL
);
CREATE table Person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    first_name varchar (100) NOT NULL ,
    last_name varchar (100) NOT NULL ,
    year_birth int NOT NULL
);